f

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,50 +1,33 @@
 steps:
-# Step 1: Restore cached packages
+# Step 1: Pull the latest image to use as a cache source
 - name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
-  id: restore-cache
+  id: pull-cache
   entrypoint: bash
-  args:
-  - -c
-  - |
-    gsutil cp gs://${_PROJECT_ID}-build-cache/consolidator-packages.tar.gz packages.tar.gz || echo "Cache not found."
-    if [ -f packages.tar.gz ]; then
-      mkdir -p ./packages
-      tar -xzf packages.tar.gz -C ./packages
-    fi
+  args: [ '-c', 'docker pull ${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest || exit 0' ]
 
-# Step 2: Install/update packages into the local 'packages' directory
+# Step 2: Build the image, using the pulled image as a cache
 - name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
-  id: pip-install
-  entrypoint: bash
+  id: build
+  entrypoint: docker
   args:
-  - -c
-  - |
-    pip install --target=./packages --upgrade --break-system-packages -r requirements.txt
-  waitFor: ['restore-cache']
+  - build
+  - --cache-from
+  - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest'
+  - --tag
+  - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:$BUILD_ID'
+  - --tag
+  - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest'
+  - '.'
+  waitFor: ['pull-cache']
 
-# Step 3: Save the updated packages to the cache
+# Step 3: Push the new image to Artifact Registry
 - name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
-  id: save-cache
-  entrypoint: bash
-  args:
-  - -c
-  - |
-    tar -czf packages.tar.gz -C ./packages .
-    gsutil cp packages.tar.gz gs://${_PROJECT_ID}-build-cache/consolidator-packages.tar.gz
-  waitFor: ['pip-install']
+  id: push
+  entrypoint: docker
+  args: ['push', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest']
+  waitFor: ['build']
 
-# Step 4: Build and Push the image
-- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
-  id: build-and-push
-  entrypoint: bash
-  args:
-  - -c
-  - |
-    docker build --tag '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:$BUILD_ID' --tag '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest' .
-    docker push '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}' --all-tags
-  waitFor: ['save-cache']
-
-# Step 5: Download config and deploy
+# Step 4: Download config and deploy
 - name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
   id: deploy
   entrypoint: sh
@@ -55,9 +38,9 @@ steps:
     cd terraform
     terraform init -backend-config="prefix=cloud-spanner-demo/${_PROJECT_SUFFIX}/consolidator"
     terraform apply -auto-approve -var="image_tag=$BUILD_ID"
-  waitFor: ['build-and-push']
+  waitFor: ['push']
 
-# Step 6: Clean up old images
+# Step 5: Clean up old images
 - name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
   id: cleanup-images
   entrypoint: bash
